#!/bin/sh -e

export DESTDIR="$1"

sed -i "/subdir('tests')/d" meson.build

meson \
    --sysconfdir=/etc \
    -Dgir=false \
    -Djasper=false \
    -Dpng=true \
    -Ddocs=false \
    -Dman=false \
    -Dgio_sniffing=false \
    -Dinstalled_tests=false \
    -Dbuiltin_loaders=all \
    . output

ninja -C output
ninja -C output install
