#!/bin/sh -e


# Reported 20-27% performance improvements.
# See: "PythonNoSemanticInterpositionSpeedup"

patch -p1 < python3-always-pip.patch
for patch in patch-*; do
    patch -p0 < "$patch"
done

./configure \
    --enable-shared \
    --with-system-expat \
    --with-system-ffi \
    --with-ensurepip=yes \
    --without-doc-strings

make CC=cc
make DESTDIR="$1" install

ln -s python3 "$1/usr/local/bin/python"
ln -s pip3    "$1/usr/local/bin/pip"

# Make static library writable.
#chmod u+w "$1/usr/local/lib/libpython"*

# Let's make some kind of effort to reduce the overall
# size of Python by removing a bunch of rarely used and
# otherwise useless components.
#
# This can't be done via ./configure as the build system
# doesn't give you this much control over the process.
#{
#    cd "$1/usr/local/lib/python"*
#    rm -rf test ./*/test ./*/tests
#    rm -rf pydoc* idlelib turtle* config-* ensurepip
#
#    cd "$1/usr/local/bin"
#    rm -f pydoc* idle*
#}
