#!/bin/sh -e

make \
    prefix=/usr \
    CC="${CC:-cc} $CFLAGS $CXXFLAGS" \
    -f unix/Makefile generic

make \
    prefix="$1/usr/local" \
    MANDIR="$1/usr/local/share/man/man1" \
    -f unix/Makefile install
