#!/bin/sh -e

#for patch in patch-*; do
#    patch -p0 < "$patch"
#done

export DESTDIR="$1"

# Remove 'libelf' and 'util-linux' dependencies.
#sed -i 's/HAVE_LIBELF/HAVE_KISS/'      gio/meson.build
#sed -i 's/libmount_dep.found()/false/' meson.build

# Don't build tests/fuzzing stuff.
find . -type f -name meson.build -exec \
    sed -i "/subdir('tests')/d;/subdir('fuzzing')/d" {} +

#export CC=cc
export CXXFLAGS="$CXXFLAGS -I/usr/local/include"
export CFLAGS="$CFLAGS -I/usr/local/include"
export LDFLAGS="$LDFLAGS -L/usr/local/lib"


meson \
    -Dlibmount=disabled \
    -Dinstalled_tests=false \
    -Ddefault_library=both \
    -Dman=false \
    -Dfam=false \
    -Dinternal_pcre=true \
    -Dselinux=disabled \
    -Dxattr=false \
    -Diconv=external \
    -Dnls=disabled \
    . build

ninja -C build
ninja -C build install
