#!/bin/sh -e

export CFLAGS="$CFLAGS -fcommon -D_XOPEN_SOURCE=700"
export PERL5LIB="$PWD/usr/local/libdata/perl5/site_perl/amd64-openbsd"
export PATH="$PATH:$PWD/xxd"
export FLEX=flex

for p in html-parser html-tagset; do (
    cd "$p"

    perl Makefile.PL

    make
    make DESTDIR="$PWD/.." install
) done

# Build standalone xxd to remove VIM requirement
cc xxd/xxd.c -o xxd/xxd

gmake \
    TARGET=gtk3

gmake \
    TARGET=gtk3 \
    DESTDIR="$1" \
    NETSURF_HOMEPAGE=https://lite.duckduckgo.com/lite \
    install
