#!/bin/sh -e

#export CFLAGS="-fno-omit-frame-pointer"
for patch in *.patch; do
    patch -p1 < "$patch"
done

sed -e "/Version:/s@version@1.1@" -i libexecinfo.pc

make

install -Dm644 execinfo.h       "$1/usr/local/include/execinfo.h"
install -Dm644 stacktraverse.h  "$1/usr/local/include/stacktraverse.h"
install -Dm755 libexecinfo.a    "$1/usr/local/lib/libexecinfo.a"
install -Dm755 libexecinfo.so.1 "$1/usr/local/lib/libexecinfo.so.1"
install -Dm644 libexecinfo.pc   "$1/usr/local/lib/pkgconfig/libexecinfo.pc"
ln -s /usr/local/lib/libexecinfo.so.1 "$1/usr/local/lib/libexecinfo.so"
