#!/bin/sh -e

#for patch in patch-*; do
#    patch -p0 < "$patch"
#done

#sed -i '/gi18n.h/d' json-glib/json-glib-format.c
#    sed -i '/gi18n.h/d' json-glib/json-glib-validate.c

export DESTDIR="$1"
#export CFLAGS="$CFLAGS -I/usr/local/include/glib-2.0/glib/gi18n-lib.h"



meson \
    --sysconfdir=/etc \
    -Ddocs=false \
    -Dman=false \
    -Dintrospection=false \
    . output

ninja -C output
ninja -C output install

kiss l dbus >/dev/null 2>&1 || rm -rf "$1/usr/bin/gdbus"
