#!/bin/sh -e

export CC=cc

./configure \
    --disable-nls \
    --with-nettle-mini \
    --with-included-libtasn1 \
    --with-included-unistring \
    --enable-static \
    --without-p11-kit

make
make DESTDIR="$1" install
